
services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      - ETCD_HEARTBEAT_INTERVAL=500
      - ETCD_ELECTION_TIMEOUT=2500
    volumes:
      - etcd_data:/etcd
    ports:
      - "2379:2379"
    command: >
      etcd -advertise-client-urls http://0.0.0.0:2379
           -listen-client-urls http://0.0.0.0:2379
           -data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  pulsar:
    container_name: milvus-pulsar
    image: apachepulsar/pulsar:3.0.1
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.3.4
    command: [ "milvus", "run", "standalone" ]
    depends_on:
      - etcd
      - minio
      - pulsar
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      PULSAR_ADDRESS: pulsar:6650
      MILVUS_LOG_LEVEL: debug

volumes:
  etcd_data:
  minio_data:
  milvus_data:
